## Importing libraries and csv file

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
train = pd.read_csv(r'C:\Users\Smriti Priya\Desktop\Hackathon\train.csv')
test = pd.read_csv(r'C:\Users\Smriti Priya\Desktop\Hackathon\test.csv')

In [4]:
print(train.shape, test.shape)

(381109, 12) (127037, 11)


In [5]:
display(train.head(), test.head())

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0   1    Male   44                1         28.0                   0   
1   2    Male   76                1          3.0                   0   
2   3    Male   47                1         28.0                   0   
3   4    Male   21                1         11.0                   1   
4   5  Female   29                1         41.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0   > 2 Years            Yes         40454.0                  26.0      217   
1    1-2 Year             No         33536.0                  26.0      183   
2   > 2 Years            Yes         38294.0                  26.0       27   
3    < 1 Year             No         28619.0                 152.0      203   
4    < 1 Year             No         27496.0                 152.0       39   

   Response  
0         1  
1         0  
2         1  
3         0  
4         0

id Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  381110   Male   25                1         11.0                   1   
1  381111   Male   40                1         28.0                   0   
2  381112   Male   47                1         28.0                   0   
3  381113   Male   24                1         27.0                   1   
4  381114   Male   27                1         28.0                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0    < 1 Year             No         35786.0                 152.0       53  
1    1-2 Year            Yes         33762.0                   7.0      111  
2    1-2 Year            Yes         40050.0                 124.0      199  
3    < 1 Year            Yes         37356.0                 152.0      187  
4    < 1 Year             No         59097.0                 152.0      297

In [6]:
display(train.describe(), test.describe())

id            Age  Driving_License    Region_Code  \
count  381109.000000  381109.000000    381109.000000  381109.000000   
mean   190555.000000      38.822584         0.997869      26.388807   
std    110016.836208      15.511611         0.046110      13.229888   
min         1.000000      20.000000         0.000000       0.000000   
25%     95278.000000      25.000000         1.000000      15.000000   
50%    190555.000000      36.000000         1.000000      28.000000   
75%    285832.000000      49.000000         1.000000      35.000000   
max    381109.000000      85.000000         1.000000      52.000000   

       Previously_Insured  Annual_Premium  Policy_Sales_Channel  \
count       381109.000000   381109.000000         381109.000000   
mean             0.458210    30564.389581            112.034295   
std              0.498251    17213.155057             54.203995   
min              0.000000     2630.000000              1.000000   
25%              0.000000    24405.000000             29.000000   
50%              0.000000    31669.000000            133.000000   
75%              1.000000    39400.000000            152.000000   
max              1.000000   540165.000000            163.000000   

             Vintage       Response  
count  381109.000000  381109.000000  
mean      154.347397       0.122563  
std        83.671304       0.327936  
min        10.000000       0.000000  
25%        82.000000       0.000000  
50%       154.000000       0.000000  
75%       227.000000       0.000000  
max       299.000000       1.000000

id            Age  Driving_License    Region_Code  \
count  127037.000000  127037.000000    127037.000000  127037.000000   
mean   444628.000000      38.765903         0.998134      26.459866   
std     36672.567411      15.465814         0.043152      13.209916   
min    381110.000000      20.000000         0.000000       0.000000   
25%    412869.000000      25.000000         1.000000      15.000000   
50%    444628.000000      36.000000         1.000000      28.000000   
75%    476387.000000      49.000000         1.000000      35.000000   
max    508146.000000      85.000000         1.000000      52.000000   

       Previously_Insured  Annual_Premium  Policy_Sales_Channel        Vintage  
count       127037.000000   127037.000000         127037.000000  127037.000000  
mean             0.460039    30524.643576            111.800468     154.318301  
std              0.498403    16945.297103             54.371765      83.661588  
min              0.000000     2630.000000              1.000000      10.000000  
25%              0.000000    24325.000000             26.000000      82.000000  
50%              0.000000    31642.000000            135.000000     154.000000  
75%              1.000000    39408.000000            152.000000     227.000000  
max              1.000000   472042.000000            163.000000     299.000000

In [7]:
display(train.dtypes, test.dtypes)

id                        int64
Gender                   object
Age                       int64
Driving_License           int64
Region_Code             float64
Previously_Insured        int64
Vehicle_Age              object
Vehicle_Damage           object
Annual_Premium          float64
Policy_Sales_Channel    float64
Vintage                   int64
Response                  int64
dtype: object

id                        int64
Gender                   object
Age                       int64
Driving_License           int64
Region_Code             float64
Previously_Insured        int64
Vehicle_Age              object
Vehicle_Damage           object
Annual_Premium          float64
Policy_Sales_Channel    float64
Vintage                   int64
dtype: object

In [8]:
display(train.isnull().sum(), train.isnull().sum())

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
dtype: int64

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
dtype: int64

## Training Data

In [9]:
# creating catagorical features

train['Gender'] = train['Gender'].map({'Female':0, 'Male':1})
train['Vehicle_Age'] = train['Vehicle_Age'].map({'< 1 Year':0, '1-2 Year':1, '> 2 Years':2})
train['Vehicle_Damage'] = train['Vehicle_Damage'].map({'No':0, 'Yes':1})

train.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0   1       1   44                1         28.0                   0   
1   2       1   76                1          3.0                   0   
2   3       1   47                1         28.0                   0   
3   4       1   21                1         11.0                   1   
4   5       0   29                1         41.0                   1   

   Vehicle_Age  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0            2               1         40454.0                  26.0      217   
1            1               0         33536.0                  26.0      183   
2            2               1         38294.0                  26.0       27   
3            0               0         28619.0                 152.0      203   
4            0               0         27496.0                 152.0       39   

   Response  
0         1  
1         0  
2         1  
3         0  
4         0

In [10]:
X = train.drop(['id', 'Response'], axis=1)
y = train['Response']

display(X.shape, y.shape)

(381109, 10)

(381109,)

### Model Selection

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_validate, y_train, y_validate = train_test_split(X, y, test_size=0.2, random_state=25)

In [12]:
from xgboost import XGBClassifier
xgb = XGBClassifier() 

In [13]:
# Hyperparameter Tuning

from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

parameters={
 "learning_rate"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
 "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
 "min_child_weight" : [ 1, 3, 5, 7 ],
 "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
 "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]  
}

random_search = RandomizedSearchCV(xgb,
                                   param_distributions=parameters,
                                   n_iter=5,
                                   scoring='roc_auc',
                                   n_jobs=-1,
                                   cv=5,
                                   verbose=3)

random_search.fit(X,y)

Fitting 5 folds for each of 5 candidates, totalling 25 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 out of  25 | elapsed:  7.2min finished


RandomizedSearchCV(cv=5, error_score='raise-deprecating',
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1, gamma=0,
                                           learning_rate=0.1, max_delta_step=0,
                                           max_depth=3, min_child_weight=1,
                                           missing=None, n_estimators=100,
                                           n_jobs=1, nthread=None,
                                           objective='binary:logistic',
                                           random_state=0, reg_alpha=0...
                                           seed=None, silent=None, subsample=1,
                                           verbosity=1),
                   iid='warn', n_iter=5, n_jobs=-1,
                   param_distribu

In [14]:
random_search.best_estimator_

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.5, gamma=0.4,
              learning_rate=0.2, max_delta_step=0, max_depth=4,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [15]:
xgb = XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.4, gamma=0.1,
              learning_rate=0.25, max_delta_step=0, max_depth=5,
              min_child_weight=3, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

### Model Evaluation

In [16]:
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import roc_auc_score

In [17]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(xgb, X, y, cv=10)

In [18]:
score.mean()

0.8776780399388683

In [19]:
xgb.fit(X,y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.4, gamma=0.1,
              learning_rate=0.25, max_delta_step=0, max_depth=5,
              min_child_weight=3, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [20]:
xgb_pred = xgb.predict_proba(X_validate)

In [21]:
xgb_pred

array([[9.9970311e-01, 2.9690727e-04],
       [9.8347706e-01, 1.6522953e-02],
       [6.4301074e-01, 3.5698926e-01],
       ...,
       [9.0272897e-01, 9.7271025e-02],
       [7.0715696e-01, 2.9284304e-01],
       [6.7467934e-01, 3.2532066e-01]], dtype=float32)

In [22]:
xgb_pred = xgb_pred[:,1]

In [23]:
xgb_pred

array([2.9690727e-04, 1.6522953e-02, 3.5698926e-01, ..., 9.7271025e-02,
       2.9284304e-01, 3.2532066e-01], dtype=float32)

In [24]:
roc_auc_score(y_validate, xgb_pred)

0.8653780757884081

## Testing Data

In [25]:
# creating catagorical features

test['Gender'] = test['Gender'].map({'Female':0, 'Male':1})
test['Vehicle_Age'] = test['Vehicle_Age'].map({'< 1 Year':0, '1-2 Year':1, '> 2 Years':2})
test['Vehicle_Damage'] = test['Vehicle_Damage'].map({'No':0, 'Yes':1})

test.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  381110       1   25                1         11.0                   1   
1  381111       1   40                1         28.0                   0   
2  381112       1   47                1         28.0                   0   
3  381113       1   24                1         27.0                   1   
4  381114       1   27                1         28.0                   1   

   Vehicle_Age  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0            0               0         35786.0                 152.0       53  
1            1               1         33762.0                   7.0      111  
2            1               1         40050.0                 124.0      199  
3            0               1         37356.0                 152.0      187  
4            0               0         59097.0                 152.0      297

In [26]:
X_test = test.drop(['id'], axis=1)

### Prediction and Submission

In [27]:
pred = xgb.predict_proba(X_test)

In [28]:
pred = pred[:,1]

In [29]:
pred

array([4.5746088e-04, 3.0970523e-01, 3.0183896e-01, ..., 2.8900680e-04,
       2.2150928e-04, 1.2120232e-03], dtype=float32)

In [30]:
df1 = pd.DataFrame(test['id'])
df2 = pd.DataFrame(pred, columns=['Response'])
display(df1.head(3), df2.head(3))

id
0  381110
1  381111
2  381112

Response
0  0.000457
1  0.309705
2  0.301839

In [31]:
final = pd.concat([df1, df2], axis=1)

In [32]:
final.to_csv(r'C:\Users\Smriti Priya\Desktop\Hackathon\submission.csv', index=False)